---
# file: roles/ovpn/tasks/main.yml

- include: apt-install-openvpn.yml
  when: ansible_distribution == "Ubuntu"

- include: apk-install-openvpn.yml
  when: ansible_distribution == "Alpine"

- include: setup-tunnels.yml

- include: ubuntu-systemd.yml
  when: ansible_distribution_major_version == "16"

- include: ubuntu-initd.yml
  when: ansible_distribution_major_version <= "14"
