- name: Checking openvpn package
  apt: name=openvpn update_cache=yes cache_valid_time=3600 state=present

- name: Checking OVPN Config Directory
  file: path={{ openvpn_dir }} state=directory

- name: Generating OVPN config files
  template: src=ovpn.j2 dest={{ openvpn_dir }}{{ item.key }}.conf force=no
  with_dict: "{{ host.tunnel_interfaces }}"

- name: Creating local key repository
  file: path=roles/ovpn/files/{{ inventory_hostname }}/ state=directory
  delegate_to: 127.0.0.1

- name: Generate shared OVPN key files
  shell: openvpn --genkey --secret {{ item.value.secret }}
  delegate_to: 127.0.0.1
  args:
    chdir: roles/ovpn/files/shared/
    creates: "{{ item.value.secret }}"
  when: item.value.secret is defined
  with_dict: "{{ host.tunnel_interfaces }}"

- name: Copying shared OVPN key files from repo to hosts
  copy:
    src: "shared/{{ item.value.secret }}"
    dest: "{{ openvpn_dir }}"
    force: no
  when: item.value.secret is defined
  with_dict: "{{ host.tunnel_interfaces }}"

- name: Generate OVPN key files
  shell: openvpn --genkey --secret {{ item.key }}.key
  delegate_to: 127.0.0.1
  args:
    chdir: roles/ovpn/files/{{ inventory_hostname }}/
    creates: "{{ item.key }}.key"
  when: item.value.secret is undefined
  with_dict: "{{ host.tunnel_interfaces }}"

- name: Copying OVPN key files from repo to hosts
  copy:
    src: "{{ inventory_hostname }}/{{ item.key }}.key"
    dest: "{{ openvpn_dir }}"
    force: no
  when: item.value.secret is undefined
  with_dict: "{{ host.tunnel_interfaces }}"
