---
# file: roles/common/tasks/main.yml
- include: hostname.yml

- include: ubuntu16-apt-fix.yml
  when: ansible_distribution_major_version == "16"

- include: apt-cache-update.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - update
    - base

- include: apk-upgrade.yml
  when: ansible_distribution == "Alpine"
  tags:
    - update
    - base

- include: apt-pkg-install.yml
  when: ansible_distribution == "Ubuntu"
  tags: base

- include: apk-pkg-install.yml
  when: ansible_distribution == "Alpine"
  tags: base
